<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Your Name</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<nav class="menu">
  <ul>
    <li><a href="lukehome.php">Luke</a></li>
    <li><a href="tomhome.php">Tom</a></li>
    <li><a href="mikehome.php">Michael</a></li>
  </ul>
</nav>

<body class = "container">

<header>
  <a href="index.php">
    <h1>Name</h1>
    <img src="images/yourimg.jpg" alt="picture of whoever">
  </a>
</header>

<aside>
  <ul>
    <li> List item 1 </li>
    <li> List Item 2 </li>
    <li> List item etc </li>
  </ul>
</aside>