<footer class="leftbox">
  CSC 174: Advanced Font-end Web Design and Developement 
</footer>

<nav class="menu">
  <ul>
    <li><a href="luke-home.php">Freshman Fall</a></li>
    <li><a href="freshman-spring.php">Freshman Spring</a></li>
    <li><a href="sophomore.php">Sophomore Year</a></li>
    <li><a href="final-years.php">Junior and Senior Years</a></li>
  </ul>
</nav>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>