<footer class="leftbox">
  CSC 174: Advanced Font-end Web Design and Developement 
</footer>

<nav class="menu">
  <ul>
    <li><a href="mikehome.php">Home</a></li>
    <li><a href="academics.php">Academics</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="misc.php">Misc</a></li>
  </ul>
</nav>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>