<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Thomas Hogrefe</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<nav class="menu">
  <ul>
    <li><a href="lukehome.php">Luke</a></li>
    <li><a href="tomhome.php">Tom</a></li>
    <li><a href="mikehome.php">Michael</a></li>
  </ul>
</nav>

<body class = "container">

<header>
  <a href="index.php">
    <h1>Tom</h1>
    <img src="images/cockpit.jpg" alt="Tom in flight">
  </a>
</header>

<aside>
  <ul>
    <li>Political Science Major</li>
    <li>Computer Science Minor</li>
    <li>Glider Pilot</li>
  </ul>
</aside>