<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Michael Anderson</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<nav class="menu">
  <ul>
    <li><a href="lukehome.php">Luke</a></li>
    <li><a href="tomhome.php">Tom</a></li>
    <li><a href="mikehome.php">Michael</a></li>
  </ul>
</nav>

<body class = "container">

<header>
  <a href="index.php">
    <h1>Michael Anderson</h1>
    <img src="images/kayak2.jpg" alt="picture of Michael">
  </a>
</header>

<aside>
  <ul>
    <li> Michael Anderson </li>
    <li> BS Environmental Science w/ CS Minor </li>
  </ul>
</aside>