<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Luke Oluoch</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<nav class="menu">
  <ul>
    <li><a href="lukehome.php">Luke</a></li>
    <li><a href="tomhome.php">Tom</a></li>
    <li><a href="mikehome.php">Michael</a></li>
  </ul>
</nav>

<body class = "container">

<header>
  <a href="index.php">
    <h1>Luke</h1>
    <img src="images/luke.jpg" alt="picture of Luke">
  </a>
</header>

<aside>
        <ul>
            <li>Name: Luke Oluoch</li>
            <li>Major: Chemical Engineering</li>
            <li>Class Year: 2019</li>
        </ul>
        <div>A yearly retrospective about my academic experience at the University of Rochester.</div>
</aside>