<footer class="leftbox">
  CSC 174: Advanced Font-end Web Design and Developement 
</footer>

<nav class="menu">
  <ul>
    <li><a href="index.php">page1</a></li>
    <li><a href="academics.php">page2</a></li>
    <li><a href="jobs.php">page3</a></li>
    <li><a href="misc.php">pag4</a></li>
  </ul>
</nav>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>