<footer class="leftbox">
  CSC 174: Advanced Front-end Web <br> Design and Development 
</footer>

<nav class="menu-footer">
  <ul>
    <li><a href="mikehome.php">Introduction</a></li>
    <li><a href="mikeclasses.php">Academics</a></li>
    <li><a href="mikejobs.php">Jobs</a></li>
    <li><a href="mikehobbies.php">Hobbies</a></li>
  </ul>
</nav>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>