<footer class="leftbox">
  CSC 174: Advanced Front-end Web Design and Developement 
</footer>

<nav class="menu">
  <ul>
    <li><a href="tomhome.php">Introduction</a></li>
    <li><a href="tomcourses.php">Academics</a></li>
    <li><a href="tomjobs.php">Jobs</a></li>
    <li><a href="tomhobbies.php">Hobbies</a></li>
  </ul>
</nav>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>