<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Thomas Hogrefe</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<body class = "container">

<nav class="menu">
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="amandahome.php">Amanda</a></li>
    <li><a href="mikehome.php">Michael</a></li>
    <li class="is-current"><a href="tomhome.php">Tom</a></li>
  </ul>
</nav>

<header>
  <a href="tomhome.php">
    <h1 class="tom-head">Tom</h1>
    <img src="images/cockpit.jpg" alt="Tom in flight">
  </a>
</header>

<aside class="head-aside">
  <ul>
    <li>Political Science Major</li>
    <li>Computer Science Minor</li>
    <li>Glider Pilot</li>
  </ul>
</aside>