<!DOCTYPE html>
<html lang="en">

<head>
    <title>Amanda O'Donnell</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/styles.css">
</head>

<body class="container">

    <nav class="menu">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li class="is-current"><a href="amandahome.php">Amanda</a></li>
            <li><a href="mikehome.php">Michael</a></li>
            <li><a href="tomhome.php">Tom</a></li>
        </ul>
    </nav>

    <header>
        <a href="amandahome.php">
            <h1>Amanda</h1>
            <img src="images/dancing.jpg" alt="Amanda with Fellow Dancers">
        </a>
    </header>
    <aside class="head-aside">
        <ul>
            <li>Brain & Cognitive Sciences Major</li>
            <li>Computer Science and Psychology Minors</li>
            <li>Dancer</li>
        </ul>
    </aside>
