<!DOCTYPE html>
<html lang="en">

<head>
    <title>Amanda O'Donnell | Lab 1: Initial Personal Website</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pathway+Gothic+One" rel="stylesheet">
    <link rel="stylesheet" href="css/styles.css">
</head>
<nav class="menu">
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="amandahome.php">Amanda</a></li>
    <li><a href="mikehome.php">Michael</a></li>
    <li><a href="tomhome.php">Tom</a></li>
  </ul>
</nav>

<body class="container">
    <header>
        <a href="amandahome.php">
            <h1>Amanda</h1>
            <img src="images/amanda.jpg" alt="Photo of Amanda">
        </a>
    </header>
    <aside>
        <ul>
            <li>Brain & Cognitive Sciences Major</li>
            <li>Computer Science and Psychology Minors</li>
            <li>Dancer</li>
        </ul>
    </aside>