<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Michael Anderson</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<body class = "container">

<nav class="menu">
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="amandahome.php">Amanda</a></li>
    <li class="is-current"><a href="mikehome.php">Michael</a></li>
    <li><a href="tomhome.php">Tom</a></li>
  </ul>
</nav>

<header>
  <a href="mikehome.php">
    <h1>Michael</h1>
    <img src="images/kayak.jpg" alt="picture of Michael">
  </a>
</header>

<aside class="head-aside">
  <ul>
    <li> Environmental Science Major </li>
    <li> Computer Science Minor </li>
    <li> Kayaker </li>
  </ul>
</aside>