<!DOCTYPE HTML>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Timbuktu</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<nav class="menu">
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="lukehome.php">Luke</a></li>
    <li><a href="tomhome.php">Tom</a></li>
    <li><a href="mikehome.php">Michael</a></li>
  </ul>
</nav>

<body class = "container">

<header>
  <a href="index.php">
    
  </a>
</header>

<!-- <aside>
  <ul>

  </ul>
</aside> -->