<footer class="leftbox">
  CSC 174: Advanced Font-end Web Design and Developement 
</footer>

<nav class="menu">
  <ul>
    <li><a href="tomhome.php">Home</a></li>
    <li><a href="jobs.php">Jobs</a></li>
    <li><a href="courses.php">Courses</a></li>
    <li><a href="hobbies.php">Soaring</a></li>
  </ul>
</nav>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="js/menu-highlighter.js"></script>

</body>

</html>